import { ArrowRight, Heart, Minus, Plus, ShoppingBag, Trash2, X } from 'lucide-react'
import ProductCard, { ProductArt } from './ProductCard.jsx'
import { formatINR } from '../utils/pricing.js'

export default function CartDrawer({ mode, open, items, subtotal, onClose, onQuantity, onRemove, onAddToCart, onToggleWishlist, onCheckout }) {
  if (!open) return null
  const isWishlist = mode === 'wishlist'
  return <div className="drawer-scrim" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><aside className="cart-drawer" aria-label={isWishlist ? 'Wishlist' : 'Shopping cart'}><header><div><span className="eyebrow">PCFORGE {isWishlist ? 'SAVED FOR LATER' : 'SHOPPING CART'}</span><h2>{isWishlist ? 'Your wishlist' : 'Your cart'} <small>{items.length}</small></h2></div><button className="drawer-close" onClick={onClose} aria-label="Close"><X /></button></header>
    {isWishlist ? items.length ? <div className="wishlist-grid">{items.map((product) => <ProductCard key={product.id} product={product} compact wishlisted onAdd={onAddToCart} onWishlist={onToggleWishlist} />)}</div> : <div className="cart-empty"><Heart size={35} /><h3>Save a few favourites.</h3><p>Use the heart on any sample product to keep it here.</p></div> : items.length ? <><div className="cart-items">{items.map((item) => <article className="cart-item" key={item.key}><div className="cart-item-icon"><ProductArt icon={item.icon} tone={item.tone || 'blue'} image={item.image} alt={`${item.name} representative component photo`} small /></div><div className="cart-item-info"><span>{item.kindLabel}</span><b>{item.name}</b>{item.specs?.slice(0, 2).map((spec) => <small key={spec}>{typeof spec === 'string' ? spec : spec.name}</small>)}<div className="quantity-control"><button onClick={() => onQuantity(item.key, item.quantity - 1)} aria-label="Decrease quantity"><Minus size={12} /></button><span>{item.quantity}</span><button onClick={() => onQuantity(item.key, item.quantity + 1)} aria-label="Increase quantity"><Plus size={12} /></button><button className="remove-item" onClick={() => onRemove(item.key)} aria-label="Remove item"><Trash2 size={13} /></button></div></div><strong>{formatINR(item.price * item.quantity)}</strong></article>)}</div><div className="cart-summary"><div><span>Sample subtotal</span><b>{formatINR(subtotal)}</b></div><p>Illustrative demo prices. No shipping or live retailer pricing is calculated.</p><button className="button button-gold full" onClick={onCheckout}>Proceed to demo checkout <ArrowRight size={15} /></button></div></> : <div className="cart-empty"><ShoppingBag size={38} /><h3>Your cart is ready for a build.</h3><p>Add components, a prebuilt PC, or your custom configuration.</p><button className="button button-gold" onClick={onClose}>Continue shopping <ArrowRight size={14} /></button></div>}
    {!isWishlist && <button className="drawer-continue" onClick={onClose}>Continue shopping</button>}
    </aside></div>
}
